# Generated by Django 4.1.6 on 2023-02-07 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_remove_event_gamer_remove_event_host_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_events', to='levelupapi.game'),
        ),
    ]
