# Generated by Django 4.1.6 on 2023-02-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0005_remove_event_host_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gamer',
            field=models.ManyToManyField(default=1, to='levelupapi.gamer'),
        ),
    ]
